---
- name: add Proxmox apt-key
  ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg 

- name: add Proxmox VE repository
  apt_repository: 
    repo: 'deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription' 
    state: present 
    filename: pve-install-repo 
    update_cache: yes

- name: Slow down raid rebuild temp
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: no
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Check if a reboot is needed
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
  notify: restart vmhost

- meta: flush_handlers
  when: reboot_required_file.stat.exists