---
- name: PROXMOX - Slow down the rebuild of RAID
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: no
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'
  when: hetzner_pve_proxmox_package_upgrades_reboot.stat.exists
  
- name: PROXMOX - Change postfix mailer type
  debconf: 
    name=postfix 
    question="postfix/main_mailer_type" 
    value="'Local only'" 
    vtype="string"

- name: PROXMOX - Install proxmox and some packages
  ansible.builtin.apt:
    pkg:
    - proxmox-ve
    - postfix
    - open-iscsi
    - python3-pip
    - cloud-init
    - libguestfs-tools
    - unzip
    - sshpass
    - telnet
    - expect
  register: hetzner_pve_proxmox_install

- name: PROXMOX - Remove old Debian kernel
  ansible.builtin.apt:
    pkg:
    - linux-image-amd64
    - os-prober
  when: hetzner_pve_proxmox_install.changed
  notify: restart vmhost

- meta: flush_handlers
  when: hetzner_pve_proxmox_install.changed 