---
- name: PROXMOX post tasks - Install required packages for unattended setup
  pip:
    name: pexpect
  when: hetzner_pve_acme_acc_registered.stat.exists == false

- name: PROXMOX post tasks - Register a new ACME account
  expect:
    command: "pvenode acme account register default {{ hetzner_pve_acme_mail }} --directory {{ hetzner_pve_acme_server }}"
    responses:
      "Do you agree to the above terms?" : 'y'
    echo: yes
  when: 
    - hetzner_pve_acme_acc_registered.stat.exists == false
    - hetzner_pve_create_acme
    
- name: PROXMOX post tasks - Register a new ACME account
  command: "{{ item }}"
  with_items:
   - "pvenode config set --acme domains={{ hetzner_pve_acme_domain }}"
   - "pvenode acme cert order"
  register: acme_result
  when:
    - hetzner_pve_proxy_cert_exists.stat.exists == false
    - hetzner_pve_create_acme

- name: PROXMOX post tasks - Copy xshock post install script
  ansible.builtin.copy:
    src: xs-install-post.sh
    dest: /tmp/xs-install-post.sh
    owner: root
    group: root
    mode: '0755'
  when: hetzner_pve_xshock_installed.stat.exists == false

- name: PROXMOX post tasks - Copy xshock post install settings
  ansible.builtin.template:
    src: xs-post-install.env.j2
    dest: /tmp/xs-install-post.env
    owner: root
    group: root
    mode: '0644'
  when: hetzner_pve_xshock_installed.stat.exists == false

- name: PROXMOX post tasks - Run of XS post installer
  ansible.builtin.shell: /tmp/xs-install-post.sh
  register: hetzner_pve_xshock_run
  notify: restart vmhost
  when: hetzner_pve_xshock_installed.stat.exists == false
  

### Remove cisofy repo - breaks "apt update"
- name: PROXMOX post tasks - Remove cisofy repository
  file:
    path: /etc/apt/sources.list.d/cisofy-lynis.list
    state: absent

- name: PROXMOX post tasks - Update Debian repositories
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644

- name: PROXMOX post tasks - Install custom packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    update_cache: yes
  with_items: "{{ hetzner_pve_custom_packages }}"
  

- meta: flush_handlers