---
- include_tasks: 01_os_prepare.yml

- include_tasks: 02_os_setup.yml
  when: hetzner_pve_installed.stat.exists == false

- include_tasks: 03_proxmox_prepare.yml
  when: hetzner_pve_installed.stat.exists == false

- include_tasks: 04_proxmox_setup.yml
  when: hetzner_pve_installed.stat.exists == false

- include_tasks: 05_proxmox_post.yml
  when: hetzner_pve_xshock_installed.stat.exists == false

- include_tasks: 07_storagebox_setup.yml
  when: hetzner_pve_storagebox_setup

- include_tasks: 08_cloudimages_setup.yml
  when: hetzner_pve_cloud_images_setup

- include_tasks: 09_opnsense_prepare.yml
  when: hetzner_pve_setup_opnsense


